name: mail_client

packages:
  - packages/*
  - apps/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze --no-fatal-infos
    description: Run flutter analyze in all packages

  format:
    exec: dart format --set-exit-if-changed .
    description: Format all Dart files

  test:
    exec: flutter test
    description: Run tests in all packages
    packageFilters:
      dirExists: test

  clean:
    exec: flutter clean
    description: Clean all packages

  build:web:
    exec: flutter build web --wasm --release
    description: Build web app with WASM
    packageFilters:
      scope: mail_app

  build:windows:
    exec: flutter build windows --release
    description: Build Windows app
    packageFilters:
      scope: mail_app

  build:android:
    exec: flutter build appbundle --release
    description: Build Android app bundle
    packageFilters:
      scope: mail_app

  build:ios:
    exec: flutter build ipa --release
    description: Build iOS app
    packageFilters:
      scope: mail_app
