name: mail_protocol
description: Email protocol implementations (IMAP, SMTP, POP3) and OAuth2 authentication.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  mail_core:
    path: ../mail_core
  enough_mail: ^2.1.7
  dio: ^5.7.0
  xml: ^6.5.0
  logger: ^2.5.0
  collection: ^1.19.1

dev_dependencies:
  test: ^1.25.15
  mocktail: ^1.0.4
